### ISSUE TITLE
Consider adding a hook for plugins to disable other plugins

### ISSUE THREAD

**Issue by hukkin** [executablebooks/mdformat#234]
https://github.com/executablebooks/mdformat-myst/pull/9#issuecomment-867065882

**Comment by LecrisUT** [comment]
I think best way to design this is to read for `.mdformat.yaml` in each folder, and merge the options of the last given `.mdformat.yaml`. Then expose an option of a dict where we define the keys as the plugins we want to load, and the values are how we configure, e.g.:

```yaml
#.mdformat.yaml
plugins:
  mdformat-gfm:
---
#docs/.mdformat.yaml
plugins:
  mdformat-myst:
    args: [ --dollarmath ]
    exclude: README.md
  mdformat-gfm:
    include: README.md
```
