### ISSUE TITLE
safeguard check that ensures that Markdown AST stays untouched

### ISSUE THREAD

**Issue by Borda** [executablebooks/mdformat#247]
### Describe the problem

Error: Could not format "/code/README.md".

The formatted Markdown renders to different HTML than the input Markdown. This
is likely a bug in mdformat. Please create an issue report here, including the
input Markdown: https://github.com/executablebooks/mdformat/issues

### Link to your repository or website

https://github.com/PyTorchLightning/pytorch-lightning/pull/8673

### Steps to reproduce

bot: https://results.pre-commit.ci/run/github/178626720/1627894852.sxZO2S7eSFu1ruIy9aSWfA
repo/PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/8673

### The version of Python you're using

3.8

### Versions of your packages

```yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.7
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat_frontmatter
        exclude: CHANGELOG.md
```

### Additional context

NOt really sure what is happening, so follow the instructions in the error message...
