### ISSUE TITLE
Link tokens [] are escaped

### ISSUE THREAD

**Issue by mdeweerd** [executablebooks/mdformat#311]
### Describe the bug

```markdown
- [KiCAD](KiCAD)
- [KiCAD - Scripts](KiCAD - Scripts)
- [KiCAD - CNC](KiCAD - CNC)
```
is converted to
```markdown
- [KiCAD](KiCAD)
- \[KiCAD - Scripts\](KiCAD - Scripts)
- \[KiCAD - CNC\](KiCAD - CNC)
```

Rendering the links useless.

There are links that are properly resolved in gitlab.

**expectation**
The link is maintained.

**problem**
This is a problem because this breaks the expected behaviour after applying mdformat.

### Reproduce the bug

Apply mdformat on

```markdown
- [KiCAD](KiCAD)
- [KiCAD - Scripts](KiCAD - Scripts)
- [KiCAD - CNC](KiCAD - CNC)
```

### List your environment

I suggest you update the hint to get the version (jupyter-hook does not exist).

```
$ mdformat --version
mdformat 0.7.13 (mdformat_frontmatter: 0.4.1, mdformat_gfm: 0.3.5,
mdformat_tables: 0.4.1)
$ python --version
Python 3.9.10
```

pre-commit configuration:
```
  - repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.13
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat  # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, '75', --number]
        additional_dependencies:
          - mdformat-toc
```
