### ISSUE TITLE
mdformat escapes backslashes in LaTeX expressions

### ISSUE THREAD

**Issue by ycrouin** [executablebooks/mdformat#325]
### Describe the bug

Before formatting
![Screenshot from 2022-05-24 14-40-37](https://user-images.githubusercontent.com/79843522/170038337-9437b3f4-7d23-49d5-9b44-9be8b60d100e.png)
After formatting
![Screenshot from 2022-05-24 14-40-55](https://user-images.githubusercontent.com/79843522/170038354-38e0110b-d08e-4930-9a9c-742951839568.png)

### Reproduce the bug

I'm using pre-commit with the following configuration

```yaml
# .pre-commit.config.yaml
repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa
        entry: nbqa mdformat --number --nbqa-md
        name: nbqa-mdformat
        alias: nbqa-mdformat
        additional_dependencies: [mdformat==0.7.14, mdformat_tables==0.4.1]
```

`pre-commit run --all-files`

### List your environment

- pre-commit: 2.19.0
- python: 3.8.10
- os: Linux Ubuntu 20.04
