### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by v-goncharenko** [executablebooks/mdformat#334]
### Context

I use Latex in my Markdown, then it is rendered with MathJax (in Jupyter Notebook).

But now `mdformat` reformats my Latex code as follows:

```bash
$$
-    "\\begin{equation}\n",
+    "\\\\begin{equation}\n",

-    "d(x, y) = \\sqrt{\\sum_{i = 1}^n (x_i - y_i)^2}\n",
+    "d(x, y) = \\\\sqrt{\\\\sum\\_{i = 1}^n (x_i - y_i)^2}\n",

-    "\\end{equation}\n",
+    "\\\\end{equation}\n",
$$
```

So after formatting it stops to be valid Latex and renders as string.

### Proposal

Escape Latex notation in mdformat.

1. Easy way - just escape (left as is) everything inside `$$ ... $$` block (and maybe in `$ ... $` block). But this is error prone =(
2. Harder way - borrow parser ideas from Jupyter, MathJax, etc. This requires some research.

**Comment by hukkin** [comment]
`mdformat-myst` plugin supports the dollar math syntax that you use. Please try installing it. It is possible that the support discontinuous though in which case you may need to create a separate plugin, see https://github.com/executablebooks/mdformat/issues/330#issuecomment-1167047766 

Nonetheless, the syntax is not included in CommonMark spec so mdformat "core" will not support it.

**Comment by v-goncharenko** [comment]
Yes, this seem to solve the problem, thanks!

I use it with [nbQA](https://github.com/nbQA-dev/nbQA) and my final config for `mdformat` looks like this:

```yaml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==22.6.0]
      - id: nbqa-isort
        additional_dependencies: [isort==5.10.1]
      - id: nbqa-flake8
        additional_dependencies: [flake8==3.9.2]
      - id: nbqa-mdformat
        name: nbqa-mdformat
        entry: nbqa mdformat
        alias: nbqa-mdformat
        additional_dependencies:
          - mdformat==0.7.14
          - mdformat-myst
```
