### ISSUE TITLE
URL in image path is falsely patched with ,<>

### ISSUE THREAD

**Issue by Borda** [executablebooks/mdformat#416]
### Describe the bug

**context**
Formating status badges from Azure, just copy paste the provided code by Azure devops

**expectation**
keep it as it is:
`[![Build Status](https://dev.azure.com/Lightning-AI/lightning/_apis/build/status%2Fpytorch-lightning%20(GPUs)?branchName=master)](https://dev.azure.com/Lightning-AI/lightning/_build/latest?definitionId=24&branchName=master)`

**bug**
with added <> it is not rendered as image

```
[![Build Status](<https://dev.azure.com/Lightning-AI/lightning/_apis/build/status%2Fpytorch-lightning%20(GPUs)?branchName=master>)](https://dev.azure.com/Lightning-AI/lightning/_build/latest?definitionId=24&branchName=master)
```

### Reproduce the bug

using pre-commit hook:
```yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
```
