### ISSUE TITLE
Add configuration for requiring plugins

### ISSUE THREAD

**Issue by hukkin** [executablebooks/mdformat#460]
### Context

It would be useful to have configuration to require a set of plugins and ignore other installed plugins.

### Proposal

Add configuration options `enable_extensions` and `enable_codeformatters`. These take a list of strings that are plugin entry point names e.g. `tables` for `mdformat-tables` and `python` for `mdformat-black`.

If a plugin is installed but not mentioned in an "enable" list, it will be disabled. If a plugin is mentioned in an "enable" list but not installed, mdformat exits with a non-zero code, informing the user that either configuration needs to change or plugin be installed.

On the CLI I think this is intuitively a comma separated list because of the plural form, which is a shame because it's different from `--exclude` which takes a single value but can be used multiple times. The other option is to change the configuration name to singular form, and use it like `--exclude` on the CLI, but the singular forms are not so nice in the TOML file...

Not sure about the naming with "enable". This feature is really "require, enable, and override the default of enable all". Would "require" be better for the name?

An alternative for the plugin IDs in "enable" lists is to use distribution package name instead of entry point names, but there can be distributions with many plugins, so that would disallow fine control. The true unique ID of a plugin really is a tuple (distribution_name, entry_point_name).

**Comment by hukkin** [comment]
Perhaps `require_extensions` and `require_codeformatters` and a separate `ignore_unrequired_plugins` boolean is better?

**Comment by hukkin** [comment]
Another naming option: `use_extensions` and `use_codeformatters`

**Comment by sanmai-NL** [comment]
I prefer `use` with clear docs what happens in the fault path.

**Comment by hukkin** [comment]
I agree that might be best. I think with `require` most users would want to use `ignore_unrequired_plugins=true` so two settings would be needed. With `use` I think its fair to assume that `ignore_unrequired_plugins` is an implicit consequence of `use`.

The CLI flags might then look like:
```sh
# Use some
--use-extensions gfm,tables
--use-codeformatters python,go

# Disable all
--use-extensions ''
--use-codeformatters ''

# Use all
--use-extensions all					# Special value (the default)
--use-codeformatters all				# Special value (the default)
```

And same in TOML:
```toml
# Use some
use_extensions = ["gfm", "tables"]
use_codeformatters = ["python", "go"]

# Disable all
use_extensions = []
use_codeformatters = []

# Use all
use_extensions = "all"					# Special value (the default)
use_codeformatters = "all"				# Special value (the default)
```
